format_version: 2
pipelines:
  Dummy-Container-Build:
    group: Dummy-Container-Group
    label_template: "1.0.0.${COUNT}"
    materials:
      backend:
        git: https://github.com/karelbemelmans/dummy-container
        branch: master
    stages:
      - Build:
          clean_workspace: true
          jobs:
            Docker-Build:
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/bash
                    arguments:
                    - -c
                    - docker build .
                - exec:
                    run_if: passed
                    command: /bin/bash
                    arguments:
                    - ./scripts/hello-world.sh
